export const categories = [
  {
    "name": "Bakeware",
    "slug": "bakeware",
    "image": "/Bakeware/Adjustable Cake Ring.png",
    "images": [
      "/Bakeware/Adjustable Cake Ring.png",
      "/Bakeware/Baking Paper Roll.png",
      "/Bakeware/Baking Sheet 16_ _ 24.png",
      "/Bakeware/Cake Topper.png",
      "/Bakeware/Cake Turn Table.png",
      "/Bakeware/Cream Leveller.png",
      "/Bakeware/Cream Whipper.png",
      "/Bakeware/Cube Shape Bread Mould.png",
      "/Bakeware/Cutting Mat.png",
      "/Bakeware/Cylindrical Bread Mould.png",
      "/Bakeware/Digital Weight Scale.png",
      "/Bakeware/Disposable Piping Bag.png",
      "/Bakeware/Donut Tray.png",
      "/Bakeware/Electric Spray Gun.png",
      "/Bakeware/Fancy Cake Mould (Character _ Theme Based).png",
      "/Bakeware/Hand Mixer (Lexical _ Netmego).png",
      "/Bakeware/Oven Thermometer.png",
      "/Bakeware/Pastry Collar.png",
      "/Bakeware/Pinata Cake Tray (Heart_Round).png",
      "/Bakeware/Piping Nozzels.png",
      "/Bakeware/Plastic Measuring Cup 4 pc set.png",
      "/Bakeware/Plastic Scrapper Set.png",
      "/Bakeware/Popsicle Mould.png",
      "/Bakeware/SS Cookie Cutter Set.png",
      "/Bakeware/Silicone Chocolate Mould.png",
      "/Bakeware/Silicone Heart Cake Mould.png",
      "/Bakeware/Silicone Loaf Mould.png",
      "/Bakeware/Silicone Sheet.png",
      "/Bakeware/Silicone Square Mould.png",
      "/Bakeware/Square Brownie Tray.png",
      "/Bakeware/Square Lockable Cake Mould (18_20_22 cm).png",
      "/Bakeware/Teflon Pie Dish (3_ & 4_).png",
      "/Bakeware/Triangle Shape Bread Mould.png",
      "/Bakeware/Wedding _ Congratulations Cutter Set.png",
      "/Bakeware/Welding Square Cake Mould - 2_ Height.png",
      "/Bakeware/Welding Square Cake Mould - 3_ Height.png"
    ]
  },
  {
    "name": "Barware",
    "slug": "barware",
    "image": "/Barware/30 ml Opilser Glass.png",
    "images": [
      "/Barware/30 ml Opilser Glass.png",
      "/Barware/30 ml Shot Glass.png",
      "/Barware/Bar Butler.png",
      "/Barware/Bar Caddy.png",
      "/Barware/Bar Mesh Roll.png",
      "/Barware/Bar Spoon Coin Tail SS.png",
      "/Barware/Bar Strainer.png",
      "/Barware/Bar Strip & Bar Mat.png",
      "/Barware/Beer Tower.png",
      "/Barware/Bottle Stopper.png",
      "/Barware/Brass Peg Measurer (Plain & Handle).png",
      "/Barware/Condinment Tray.png",
      "/Barware/Glass Rimmer.png",
      "/Barware/Ice Cream Cup.png",
      "/Barware/Manual Ice Crusher.png",
      "/Barware/Multi Opener.png",
      "/Barware/PC Tong.png",
      "/Barware/Pourer.png",
      "/Barware/Regular Cocktail Shakers.png",
      "/Barware/SS Condinment Holder.png",
      "/Barware/Water Jug 1 Ltr.png",
      "/Barware/Wine Bottle Stopper.png",
      "/Barware/Wine Opener.png",
      "/Barware/Wire Glass Hanger.png"
    ]
  },
  {
    "name": "Buffetware",
    "slug": "buffetware",
    "image": "/Buffetware/Basket with roll cover (2).png",
    "images": [
      "/Buffetware/Basket with roll cover (2).png",
      "/Buffetware/Basket with roll cover.png",
      "/Buffetware/Beverage Dispenser 8 Ltr.png",
      "/Buffetware/Brown Galena Electric Soup Warmer Cap.png",
      "/Buffetware/Cereal Dispenser (2).png",
      "/Buffetware/Cereal Dispenser Double 4 Ltr_2.png",
      "/Buffetware/Cereal Dispenser Revolving 4 Ltr_3.png",
      "/Buffetware/Cereal Dispenser Single 4 Ltr.png",
      "/Buffetware/Cereal Dispenser Single 7 Ltr.png",
      "/Buffetware/Cereal Dispenser Triple 4 Ltr_3.png",
      "/Buffetware/Cereal Dispenser.png",
      "/Buffetware/Coffee Decanter Cap 1.8 Ltr.png",
      "/Buffetware/Coffee Urn 10.5 Ltr.png",
      "/Buffetware/Cooling Display Set.png",
      "/Buffetware/Cups Dispenser Revolving.png",
      "/Buffetware/Display Risers.png",
      "/Buffetware/Double Beverage Dispenser 8 Ltr_2.png",
      "/Buffetware/Electric Soup Warmer Cap.png",
      "/Buffetware/Galena Electric Soup Warmer Cap.png",
      "/Buffetware/Heating Lamp (2).png",
      "/Buffetware/Heating Lamp (3).png",
      "/Buffetware/Heating Lamp (4).png",
      "/Buffetware/Heating Lamp.png",
      "/Buffetware/Hot & Cold Beverage Dispenser (2).png",
      "/Buffetware/Hot & Cold Beverage Dispenser (3).png",
      "/Buffetware/Hot & Cold Beverage Dispenser.png",
      "/Buffetware/Juice Dispenser (2).png",
      "/Buffetware/Juice Dispenser (3).png",
      "/Buffetware/Juice Dispenser.png",
      "/Buffetware/Marbella Milk Urn 5 Ltr.png",
      "/Buffetware/Merabella Beverage Dispenser 5 Ltr.png",
      "/Buffetware/Merabella Double Beverage Dispenser 5 Ltr.png",
      "/Buffetware/Merabella Half Moon Beverage Dispenser 5 Ltr _ 2.png",
      "/Buffetware/Rectangular Electric Chafer.png",
      "/Buffetware/Round Electric Chafer with glass lid cap.png",
      "/Buffetware/SS Round Electric Chafer.png",
      "/Buffetware/SS electric soup warmer cap.png",
      "/Buffetware/Snack Warmer Concepts.png",
      "/Buffetware/Soup Warmer (2).png",
      "/Buffetware/Soup Warmer (3).png",
      "/Buffetware/Soup Warmer (4).png",
      "/Buffetware/Soup Warmer.png",
      "/Buffetware/Stainless Steel Electric Chafer Cap.png",
      "/Buffetware/Wooden Risers (2).png",
      "/Buffetware/Wooden Risers Eclipse.png",
      "/Buffetware/Wooden Risers Square.png",
      "/Buffetware/Wooden Risers.png",
      "/Buffetware/X Shape Beverage Dispenser 5 Ltr.png"
    ]
  },
  {
    "name": "Chafing Dish",
    "slug": "chafing-dish",
    "image": "/Chafing Dish/Oblong Full Glass Chafer W_ Neo Legs.png",
    "images": [
      "/Chafing Dish/Oblong Full Glass Chafer W_ Neo Legs.png",
      "/Chafing Dish/Oblong Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Oblong Glass Chafer.png",
      "/Chafing Dish/Oblong Rose Gold Full Glass Chafer W_ Diamond Legs RG.png",
      "/Chafing Dish/Oblong Rose Gold Full Glass Chafer W_ Neo Legs.png",
      "/Chafing Dish/Oblong Rose Gold Glass Chafer W_ Diamond Legs RG Item - 768_DL_RG.png",
      "/Chafing Dish/Oblong Rose Gold Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Oblong Rose Gold Glass Chafer W_ E.E. & Frame.png",
      "/Chafing Dish/Rectangular Full Glass Chafer W_Diamond Legs.png",
      "/Chafing Dish/Rectangular Glass Chafer W_ Neo Legs (LC) Item - 410_NL_LC.png",
      "/Chafing Dish/Rectangular Glass Chafer.png",
      "/Chafing Dish/Rectangular Rose Gold Chafer W_ Fire Box.png",
      "/Chafing Dish/Rectangular Rose Gold Full Glass Chafer W_ Neo Legs RG.png",
      "/Chafing Dish/Rectangular Rose Gold Full Glass Chafer W_Diamond Legs.png",
      "/Chafing Dish/Rectangular Rose Gold Glass Chafer W_E.E. & Frame.png",
      "/Chafing Dish/Round All Rose Gold Glass Chafer.png",
      "/Chafing Dish/Round Full Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Round Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Round Rose Gold Full Glass Chafer W_ E.E & Frame Item - 562.png",
      "/Chafing Dish/Round Rose Gold Full Glass Chafer W_ Neo Legs.png",
      "/Chafing Dish/Round Rose Gold Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Round Rose Gold Glass Chafer W_ E.E.& Frame.png",
      "/Chafing Dish/Round SS Chafer.png",
      "/Chafing Dish/Square Full Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Square Glass Chafer W_ E.E. & Frame.png",
      "/Chafing Dish/Square Glass Chafer W_ Fire Box Item - 408_FB.png",
      "/Chafing Dish/Square Rose Gold Full Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Square Rose Gold Full Glass Chafer W_ Neo Legs.png",
      "/Chafing Dish/Square Rose Gold Glass Chafer W_ Diamond Legs.png",
      "/Chafing Dish/Square Rose Gold Glass Chafer W_ E.E. & Frame.png",
      "/Chafing Dish/Square Rose Gold Glass Chafer W_ Neo Legs (LC) RG.png",
      "/Chafing Dish/Square Rose Gold Glass Chafer.png",
      "/Chafing Dish/Square SS Chafer.png"
    ]
  },
  {
    "name": "Crockery",
    "slug": "crockery",
    "image": "/Crockery/PORCELAIN_SWAY PLATTER.png",
    "images": [
      "/Crockery/DOME BLACK PASTA PLATE.png",
      "/Crockery/DOME FULL PLATE.png",
      "/Crockery/DOME RECT PLATTER.png",
      "/Crockery/HEAVENLY BLUE PASTA BOWL.png",
      "/Crockery/MARBLE SOUP SET OBLONG.png",
      "/Crockery/PORCELAIN_AROMA COUPE BOWL AND PASTA PLATE.png",
      "/Crockery/PORCELAIN_SWAY CHARLIE PLATTER.png",
      "/Crockery/PORCELAIN_SWAY CUP SAUCER.png",
      "/Crockery/PORCELAIN_SWAY MUSE BOWL AND PASTA BOWL (2).png",
      "/Crockery/PORCELAIN_SWAY MUSE BOWL AND PASTA BOWL.png",
      "/Crockery/PORCELAIN_SWAY MUSE BOWL.png",
      "/Crockery/PORCELAIN_SWAY NAPPY BOWL.png",
      "/Crockery/PORCELAIN_SWAY PLATTER.png",
      "/Crockery/PORCELAIN_VNR GREY SPECKLE.png",
      "/Crockery/RECT PLATTER.png",
      "/Crockery/SOUP SET DUAL TONE.png",
      "/Crockery/SOUP SET GARDEN GREEN.png",
      "/Crockery/SOUP SET HEAVENLY BLUE.png",
      "/Crockery/SOUP SET MARBLE.png",
      "/Crockery/SOUP SET MINT GREEN.png"
    ]
  },
  {
    "name": "Equipments & Machinery",
    "slug": "equipments-and-machinery",
    "image": "/Equipments & Machinery Digital Catalogue/3 Burner Range.png",
    "images": [
      "/Equipments & Machinery Digital Catalogue/3 Burner Range.png",
      "/Equipments & Machinery Digital Catalogue/Bain Marie (2).png",
      "/Equipments & Machinery Digital Catalogue/Bain Marie (3).png",
      "/Equipments & Machinery Digital Catalogue/Bain Marie.png",
      "/Equipments & Machinery Digital Catalogue/Bowl Chopper.png",
      "/Equipments & Machinery Digital Catalogue/Candy Floss.png",
      "/Equipments & Machinery Digital Catalogue/Chinese Burner Range.png",
      "/Equipments & Machinery Digital Catalogue/Chocolate Fountain (2).png",
      "/Equipments & Machinery Digital Catalogue/Chocolate Fountain.png",
      "/Equipments & Machinery Digital Catalogue/Chocolate Stove.png",
      "/Equipments & Machinery Digital Catalogue/Commercial Immersion Blender.png",
      "/Equipments & Machinery Digital Catalogue/Conveyor Toaster.png",
      "/Equipments & Machinery Digital Catalogue/Deep Freezer.png",
      "/Equipments & Machinery Digital Catalogue/Dosa Bhatti.png",
      "/Equipments & Machinery Digital Catalogue/Dough Kneader.png",
      "/Equipments & Machinery Digital Catalogue/Electric Corn Steamer.png",
      "/Equipments & Machinery Digital Catalogue/Electric Dehydrator.png",
      "/Equipments & Machinery Digital Catalogue/Electric Fryer.png",
      "/Equipments & Machinery Digital Catalogue/Electric Griddle.png",
      "/Equipments & Machinery Digital Catalogue/Electric Momos Steamer (2).png",
      "/Equipments & Machinery Digital Catalogue/Electric Momos Steamer.png",
      "/Equipments & Machinery Digital Catalogue/Electric Pizza Oven.png",
      "/Equipments & Machinery Digital Catalogue/Electric Shawarma.png",
      "/Equipments & Machinery Digital Catalogue/Flat Induction Premium.png",
      "/Equipments & Machinery Digital Catalogue/Flat Induction.png",
      "/Equipments & Machinery Digital Catalogue/Gas Fryer.png",
      "/Equipments & Machinery Digital Catalogue/Gas Griddle.png",
      "/Equipments & Machinery Digital Catalogue/Gas Pizza Oven.png",
      "/Equipments & Machinery Digital Catalogue/Gas Shawarma.png",
      "/Equipments & Machinery Digital Catalogue/Ice Crusher.png",
      "/Equipments & Machinery Digital Catalogue/Idli Steamer.png",
      "/Equipments & Machinery Digital Catalogue/Indian Burner Range.png",
      "/Equipments & Machinery Digital Catalogue/Meat Mincer.png",
      "/Equipments & Machinery Digital Catalogue/Microwave.png",
      "/Equipments & Machinery Digital Catalogue/Milk Boiler.png",
      "/Equipments & Machinery Digital Catalogue/Mocktail Blender.png",
      "/Equipments & Machinery Digital Catalogue/Pasta Boiler.png",
      "/Equipments & Machinery Digital Catalogue/Pickup Counter.png",
      "/Equipments & Machinery Digital Catalogue/Planetary Mixer.png",
      "/Equipments & Machinery Digital Catalogue/Plate Warmer.png",
      "/Equipments & Machinery Digital Catalogue/Platform Trolley.png",
      "/Equipments & Machinery Digital Catalogue/Pop up Toaster.png",
      "/Equipments & Machinery Digital Catalogue/Popcorn Machine.png",
      "/Equipments & Machinery Digital Catalogue/Pulverizer.png",
      "/Equipments & Machinery Digital Catalogue/Roti Machine.png",
      "/Equipments & Machinery Digital Catalogue/Round Waffle.png",
      "/Equipments & Machinery Digital Catalogue/Salamander.png",
      "/Equipments & Machinery Digital Catalogue/Sandwich Griller.png",
      "/Equipments & Machinery Digital Catalogue/Single Burner.png",
      "/Equipments & Machinery Digital Catalogue/Sink.png",
      "/Equipments & Machinery Digital Catalogue/Softy Machine.png",
      "/Equipments & Machinery Digital Catalogue/Spiral Mixture.png",
      "/Equipments & Machinery Digital Catalogue/Sqaure Waffle.png",
      "/Equipments & Machinery Digital Catalogue/Sushi Display Counter.png",
      "/Equipments & Machinery Digital Catalogue/Tandoor.png",
      "/Equipments & Machinery Digital Catalogue/Utensils Trolley.png",
      "/Equipments & Machinery Digital Catalogue/Vegetable Cutting Machine.png",
      "/Equipments & Machinery Digital Catalogue/Water Boiler.png",
      "/Equipments & Machinery Digital Catalogue/Wok Induction.png",
      "/Equipments & Machinery Digital Catalogue/Work Table.png"
    ]
  },
  {
    "name": "Kitchen Utensils",
    "slug": "kitchen-utensils",
    "image": "/Kitchen Utensils Digital Catalogue/Skimmer.png",
    "images": [
      "/Kitchen Utensils Digital Catalogue/Skimmer.png",
      "/Kitchen Utensils Digital Catalogue/Aluminium Patila.png",
      "/Kitchen Utensils Digital Catalogue/Boning Knife.png",
      "/Kitchen Utensils Digital Catalogue/Bread Knife.png",
      "/Kitchen Utensils Digital Catalogue/Butcher Knife.png",
      "/Kitchen Utensils Digital Catalogue/Butcher _ Cleaver.png",
      "/Kitchen Utensils Digital Catalogue/Chef Knife.png",
      "/Kitchen Utensils Digital Catalogue/Chinese Palta.png",
      "/Kitchen Utensils Digital Catalogue/Chinese Strainer SS.png",
      "/Kitchen Utensils Digital Catalogue/Chinese Strainer Wooden.png",
      "/Kitchen Utensils Digital Catalogue/Chinese Wok.png",
      "/Kitchen Utensils Digital Catalogue/Cook Knife.png",
      "/Kitchen Utensils Digital Catalogue/Cooker.png",
      "/Kitchen Utensils Digital Catalogue/Cooking Ladel.png",
      "/Kitchen Utensils Digital Catalogue/Filet Knife.png",
      "/Kitchen Utensils Digital Catalogue/Fry Pan.png",
      "/Kitchen Utensils Digital Catalogue/Garnish Tray.png",
      "/Kitchen Utensils Digital Catalogue/Idli Steamer.png",
      "/Kitchen Utensils Digital Catalogue/Iron Kadhai.png",
      "/Kitchen Utensils Digital Catalogue/Kadhai.png",
      "/Kitchen Utensils Digital Catalogue/Momos Steamer - Aluminium.png",
      "/Kitchen Utensils Digital Catalogue/Momos Steamer - Steel.png",
      "/Kitchen Utensils Digital Catalogue/Non Stick Fry Pan.png",
      "/Kitchen Utensils Digital Catalogue/Pairing Knife.png",
      "/Kitchen Utensils Digital Catalogue/Parat.png",
      "/Kitchen Utensils Digital Catalogue/Patila.png",
      "/Kitchen Utensils Digital Catalogue/Polycarbonate Storage Containers.png",
      "/Kitchen Utensils Digital Catalogue/Premium Wok.png",
      "/Kitchen Utensils Digital Catalogue/Rice Strainer.png",
      "/Kitchen Utensils Digital Catalogue/Sauce Pan.png",
      "/Kitchen Utensils Digital Catalogue/Skimmer.png",
      "/Kitchen Utensils Digital Catalogue/Stock Pot.png",
      "/Kitchen Utensils Digital Catalogue/Sushi & Santoku Knife.png",
      "/Kitchen Utensils Digital Catalogue/Tandoor Seekh.png",
      "/Kitchen Utensils Digital Catalogue/Usuba Knife.png",
      "/Kitchen Utensils Digital Catalogue/Utility Knife.png",
      "/Kitchen Utensils Digital Catalogue/Vegetable Design Knife.png"
    ]
  },
  {
    "name": "Sizzlers & Wooden Items",
    "slug": "sizzlers-and-wooden-items",
    "image": "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/CAST IRON DOME SIZZLER.png",
    "images": [
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/3 IN 1 PAN PLATTER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/3 SEEKH BBQ PLATTER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/BUCKLE PLATTER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/CAST IRON DOME SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/CAST IRON SERVING POTS (2).png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/CAST IRON SERVING POTS.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/EIFFEL SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/GRILL SIZZLER LONG.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/IMP PORTION SIZZLER W_HANDLE.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/KARAHI BBQ.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/KARAHI SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/KOREAN GRILL PLATTER ROUND.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/KOREAN SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/KULCHA HANDI SET.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/ORANGE RECTANGLE GRILL SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/OVAL PREMIUM SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PIZZA BAT (2).png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PIZZA BAT.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PREMIUM JUMBO SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PREMIUM ROUND BAT SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PREMIUM ROUND DEEP SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PREMIUM SQUARE CADDY.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/PRINTED HANDLE CADDY.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/RECTANGLE CAST IRON PAN (2).png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/RECTANGLE CAST IRON PAN.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/RECTANGLE GRILL SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/ROUND BAO PLATTER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/ROUND CAST IRON SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/ROUND GRILL SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/SINGLE SEEKH BBQ PLATTER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/SIZZLER 4 IN 1.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/SQUARE DEEP SIZZLER.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/SQUARE GRILL PAN.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/SQUARE TISSUE BOX.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/STONE BOWL W_BASE.png",
      "/Kitchen Utensils Digital Catalogue/Sizzlers & Wooden Items/SUSHI BOAT.png"
    ]
  },
  {
    "name": "Tableware",
    "slug": "tableware",
    "image": "/Tableware/Serving Kadhai, Rose Gold.png",
    "images": [
      "/Tableware/37.png",
      "/Tableware/38.png",
      "/Tableware/39.png",
      "/Tableware/40.png",
      "/Tableware/41.png",
      "/Tableware/42.png",
      "/Tableware/43.png",
      "/Tableware/44.png",
      "/Tableware/45.png",
      "/Tableware/46.png",
      "/Tableware/47.png",
      "/Tableware/48.png",
      "/Tableware/Banana Platter.png",
      "/Tableware/Copper Steel Pickle Stand.png",
      "/Tableware/Copper Steel Sauce Pan (Hammered).png",
      "/Tableware/Copper Steel Tawa.png",
      "/Tableware/Gravy Bucket, Wire Handle, Double Wall, Hammer PVD Gold.png",
      "/Tableware/Hexa Tub with 2 side Brass Handle.png",
      "/Tableware/Ice Cream Cup Brass Based Hammered.png",
      "/Tableware/Ice Cream Cup Plain.png",
      "/Tableware/Ice Cream Cup SS Hammered.png",
      "/Tableware/Jasper Fry pan with Brass Handle (Hammered).png",
      "/Tableware/Kadhai with Brass Handle (Hammered).png",
      "/Tableware/Oval Boat Serving Pan with Lid (Hammered).png",
      "/Tableware/Oval Entree Dish Hammered.png",
      "/Tableware/Oval Platter SS Hammered PVD Rose Gold.png",
      "/Tableware/Recta Tub with 2 side Handle PVD Rose Gold.png",
      "/Tableware/Rectangular Pan with 2 side Brass Handle (Hammered).png",
      "/Tableware/Rectangular Pan with Brass Handle (Hammered).png",
      "/Tableware/Roti Basket.png",
      "/Tableware/Round Entree Dish PVD Gold.png",
      "/Tableware/Round Platter SS Plain Finish.png",
      "/Tableware/Round Tub with 2 side Handle Gold Pvd.png",
      "/Tableware/Sapphire Round Tub with Lid (Hammered).png",
      "/Tableware/Sauce Pan with 2 side Brass Handle (Hammered).png",
      "/Tableware/Serving Handi _ Lagan Double Wall, Hammer.png",
      "/Tableware/Serving Kadhai, Rose Gold.png",
      "/Tableware/Single Wall Premium Handi, PVD Gold.png",
      "/Tableware/Square Entree Dish Hammered.png",
      "/Tableware/Star Platter SS hammered.png",
      "/Tableware/Tea Coffee Set Premium.png",
      "/Tableware/Tea Coffee Set Royal.png",
      "/Tableware/Triangle Pan with Brass Handle (Hammered).png",
      "/Tableware/Triangular Entree Dish Plain.png",
      "/Tableware/Triangular Platter SS Hammered PVD Gold.png",
      "/Tableware/Water Pitcher Hammered.png",
      "/Tableware/Water Pitcher Imperial.png",
      "/Tableware/Water Pitcher Mat Finish.png",
      "/Tableware/ANTIQUE FRIES SERVING BASKET.png",
      "/Tableware/BELL SHOT PLATTER.png",
      "/Tableware/CASTING FISH PLATE.png",
      "/Tableware/CASTING FISH PLATTER.png",
      "/Tableware/CASTING GILLS PLATTER.png",
      "/Tableware/CASTING HANDLE BOWL.png",
      "/Tableware/CASTING PASTA BOWL.png",
      "/Tableware/CASTING ROUND FRYPAN.png",
      "/Tableware/CASTING SQUARE PAN.png",
      "/Tableware/GOLD APLLE THALI SET.png",
      "/Tableware/PREMIUM BOAT BREAD BASKET.png",
      "/Tableware/PREMIUM ROUND BREAD BASKET.png",
      "/Tableware/RECTANGLE BREAD BASKET.png",
      "/Tableware/ROUND BREAD BASKET (2).png",
      "/Tableware/ROUND BREAD BASKET.png",
      "/Tableware/SERVING COOKER (2).png",
      "/Tableware/SERVING COOKER.png",
      "/Tableware/SHOT CART.png"
    ]
  }
];
